# Generated by Django 5.0.3 on 2024-04-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=200)),
                ('query_def', models.CharField(max_length=2000)),
                ('query_len', models.IntegerField()),
                ('program', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('db', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('access', models.CharField(max_length=2000)),
                ('score', models.IntegerField()),
                ('bit_score', models.FloatField()),
                ('e_value', models.FloatField()),
                ('identity', models.IntegerField()),
                ('length', models.IntegerField()),
                ('per', models.FloatField()),
                ('query_sequence', models.TextField()),
                ('hit_sequence', models.TextField()),
                ('midline', models.TextField()),
                ('query_id', models.CharField(max_length=2000)),
                ('scientific_name', models.CharField(max_length=2000)),
            ],
        ),
    ]
